### ISSUE TITLE
Cant connect clickhouse like msyql or pg

### ISSUE THREAD

**Issue by 82253452** [lmangani/duckdb-extension-clickhouse-sql#9]
Can add this?

**Comment by lmangani** [comment]
Could you clarify your request? @82253452 

The [postgres extension](https://duckdb.org/docs/extensions/postgres.html) allows DuckDB connecting to services using the Postgres protocol, including ClickHouse server when configured to do so. This extension is mostly focused on command aliases and native DuckDB macros for compatibility with ClickHouse SQL but if you're going to use a PGSQL client your queries will run remotely so you won't likely need it.

**Comment by 82253452** [comment]
how to connect clickhouse like ATTACH 'dbname=postgres user=postgres host=127.0.0.1' AS db (TYPE POSTGRES, READ_ONLY);  i dont find it in duckdb document.

**Comment by lmangani** [comment]
@82253452 there's no such thing just yet. This extension only provides macros for now but luckily there's one for this use case:

Here's an example using ClickHouse play you can adapt to your own service:

```
CREATE OR REPLACE MACRO clickhouse(query, server := 'https://play.clickhouse.com', user := 'play', format := 'JSONEachRow') AS TABLE
    SELECT * FROM read_json_auto(concat(server, '/?default_format=', format, '&user=', user, '&query=', query));


SELECT * FROM clickhouse("SELECT number as once, number *2 as twice FROM numbers(10)")
```

**Comment by lmangani** [comment]
Closing as resolved with the only method currently available. Let us know if you have other questions.
